language: rust
cache: cargo
matrix:
  include:
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: nightly
    script: cargo build --workspace --verbose --release
    addons:
      apt:
        packages:
        - musl-tools
  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
    script: cargo build --workspace --verbose --release
  - name: Windows Binary
    os: windows
    rust: nightly
    script: cargo build --workspace --verbose --release
  - name: Centos Binary
    services: docker
    env:
      - OS_TYPE=centos OS_VERSION=7
    before_install:
      - sudo apt-get update
      - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
      - sudo service docker restart
      - sudo docker pull centos:centos${OS_VERSION}
    rust: nightly
    script: docker run --rm=true -v `pwd`:/centosbuild:rw centos:centos7 /bin/bash -c "yum groupinstall -y 'Development Tools' && curl https://sh.rustup.rs -sSf | bash -s -- -y && cd centosbuild && /root/.cargo/bin/cargo build --workspace --verbose --release"

before_deploy:
  - mkdir cfn-guard-$TRAVIS_OS_NAME
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]
    then
      cp -f target/release/cfn-guard.exe ./cfn-guard-$TRAVIS_OS_NAME/
    else
      cp ./target/release/cfn-guard ./cfn-guard-$TRAVIS_OS_NAME/
    fi
  - cp LICENSE ./cfn-guard-$TRAVIS_OS_NAME/
  - cp NOTICE ./cfn-guard-$TRAVIS_OS_NAME/
  - cp ATTRIBUTION ./cfn-guard-$TRAVIS_OS_NAME/
  - cp README.md ./cfn-guard-$TRAVIS_OS_NAME/
  - tar czvf ./cfn-guard-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz ./cfn-guard-$TRAVIS_OS_NAME

deploy:
  provider: releases
  api_key:
    secure: 8ed2476101862cfe58e962d967e80811bbb53091
  file: "./cfn-guard-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz"
  on:
    repo: omkhegde/cloudformation-guard
    tags: true
  skip_cleanup: 'true'
