language: rust
cache: cargo
matrix:
  include:
  - name: Linux Binary
    services: docker
    env:
      - OS_TYPE=centos OS_VERSION=7
    before_install:
      - sudo apt-get update
      - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s
        devicemapper"' | sudo tee /etc/default/docker > /dev/null
      - sudo service docker restart
      - sudo docker pull centos:centos${OS_VERSION}
    rust: nightly
    script: docker run --rm=true -v `pwd`:/centosbuild:rw centos:centos${OS_VERSION} /bin/bash
      -c "yum groupinstall -y 'Development Tools' && curl https://sh.rustup.rs -sSf
      | bash -s -- -y && cd centosbuild && /root/.cargo/bin/cargo build --workspace
      --verbose --release"
  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
    script: cargo build --workspace --verbose --release
  - name: Windows Binary
    os: windows
    rust: nightly
    script: cargo build --workspace --verbose --release
before_deploy:
- mkdir cfn-guard-$TRAVIS_OS_NAME
- |
  if [[ "$TRAVIS_OS_NAME" == "windows" ]]
  then
    cp -f target/release/cfn-guard.exe ./cfn-guard-$TRAVIS_OS_NAME/
  else
    cp ./target/release/cfn-guard ./cfn-guard-$TRAVIS_OS_NAME/
  fi
- cp LICENSE ./cfn-guard-$TRAVIS_OS_NAME/
- cp NOTICE ./cfn-guard-$TRAVIS_OS_NAME/
- cp ATTRIBUTION ./cfn-guard-$TRAVIS_OS_NAME/
- cp README.md ./cfn-guard-$TRAVIS_OS_NAME/
- tar czvf ./cfn-guard-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz ./cfn-guard-$TRAVIS_OS_NAME
deploy:
  provider: releases
  api_key:
    secure: VOQbnKVkxiiHHpNT9iPzTWn4NQmtrqdSDPcfQA82GEwCoUyqztA1Sy5x2ODQ/FDkUM3SYTTXoIMaOsIJzensph8mG7obST9LHl0QUoe1UOPHhKltRCtdPZdsKetWfws4mpNTGKKrrc1eG3mONKvUk46xYoGhWupm3rCOWNIZYahluCRGLJS6sDr0B3W5zgFPXeQ4y/YwM7smRjJ8Yo1WYPB77GpikEHXFx4+bUujWUtvkG+ZCgWZ/G3eGx0rmg/V1YpEzFgPyOgRrxNicPM1ieaVKWVJiqsGbcsD+9dMuae9BHgBYemeZq8Dxx3CeMgItgqaoVWV+oV5VJfl4OCVoKgjJBUKFxehuWDr20Xe4hHVmD06V3XQrQUc+kdQK3rMQDZ/QOoiLS7efke76tI2p8MwUSZmlsdae1f9J+QGYos6qvrPdVQd1JeaP52Z9b9Tcqxa5kGQIL2sz3QDQfkA7zDVJBiVUhnwFYr18OP1lXE1FWCXQvVqHcpe+DOIbu/DunMD4OoGeb/YuYKSpKI140nfP/hZ7n520r7flBJJWLwSWxv1UxJ6BbHulm1mlfS7D7jmNuS82vGaTmOiTmXgwrkuubXDrMGJsCo4Jg5HFj4ApdyVhySREvPD5DQEskfCpKPpL4PM0eauQRbaSto4iGBe5v6ntShTiNEsktHlTl4=
  file: "./cfn-guard-$TRAVIS_OS_NAME-$TRAVIS_TAG.tar.gz"
  on:
    repo: omkhegde/cloudformation-guard
    tags: true
  skip_cleanup: 'true'
